### ISSUE TITLE
请问一下怎么没有bindata

### ISSUE THREAD

**Issue by CocaineCong** [hezhizheng/go-gin-chat#2]
没有bindata

**Comment by hezhizheng** [comment]
> 没有bindata

请参考 readme 中的使用说明  https://github.com/hezhizheng/go-gin-chat#%E4%BD%BF%E7%94%A8

https://blog.hi917.com/detail/87.html @CocaineCong

**Comment by RuFeng08** [comment]
![image](https://user-images.githubusercontent.com/78016475/142484490-2617777a-6218-46a2-b7a5-9f175ef46319.png)

**Comment by RuFeng08** [comment]
Asset和Assetdir报错了怎么解决

**Comment by hezhizheng** [comment]
1、请确保已经安装了 go-bindata
2、尝试运行项目(有可能只是IDE提示问题)，提供具体报错信息。 @RuFeng08

**Comment by RuFeng08** [comment]
![image](https://user-images.githubusercontent.com/78016475/142644068-430bf130-618b-4c01-9280-3562c29e2642.png)
![image](https://user-images.githubusercontent.com/78016475/142644108-4d5c2a8d-d36c-49e9-884f-28957ffa491e.png)
运行也是报错 这两函数不存在

**Comment by RuFeng08** [comment]
go-bindata已经安装好了

**Comment by RuFeng08** [comment]
![image](https://user-images.githubusercontent.com/78016475/142644645-1be80f0c-504d-4c12-a4a5-281c920320c8.png)

**Comment by hezhizheng** [comment]
本地环境 go 1.16.9 测试没有问题
怀疑是 go-bindata 打包问题 ，建议在根目录 使用go 1.15 或以上版本运行 go-bindata 打包命令 `go-bindata -o=bindata/bindata.go -pkg=bindata ./static/... ./views/...`  ，可以检查下 bindata.go 是否存在 Asset 或者 AssetDir 方法
@RuFeng08

**Comment by hezhizheng** [comment]
已支持 embed 静态资源打包方式  无需依赖 go-bindata
更新最新代码， go版本需要 >= 1.16
