### ISSUE TITLE
SLB/DSN

### ISSUE THREAD

**Issue by yhlizl** [hezhizheng/go-gin-chat#3]
您好
想請教一下
我用了sever loading balance跟dsn後
Web調用ws時就會回傳
ERR connection_reset
請問大師知道有什麼方法嗎

**Comment by hezhizheng** [comment]
> 您好
> 想請教一下
> 我用了sever loading balance跟dsn後
> Web調用ws時就會回傳
> ERR connection_reset
> 請問大師知道有什麼方法嗎

贴一下你的配置看看？@yhlizl

**Comment by yhlizl** [comment]
> > 您好
> > 想請教一下
> > 我用了sever loading balance跟dsn後
> > Web調用ws時就會回傳
> > ERR connection_reset
> > 請問大師知道有什麼方法嗎
> 
> 贴一下你的配置看看？@yhlizl

抱歉因為是公司的slb
我也不清楚裡面配置 我是開一個TCP PORT 8666給整個頁面
然後ws的寫法是跟你一致的
請問你知道什麼情況下會ERR_CONNECTION_RESE嗎
我有查可能是client問slb的時候 回傳sever位置
Ip有被改變
是這樣嗎
感謝大大

**Comment by hezhizheng** [comment]
> > > 您好
> > > 想請教一下
> > > 我用了sever loading balance跟dsn後
> > > Web調用ws時就會回傳
> > > ERR connection_reset
> > > 請問大師知道有什麼方法嗎
> > 
> > 
> > 贴一下你的配置看看？@yhlizl
> 
> 抱歉因為是公司的slb
> 我也不清楚裡面配置 我是開一個TCP PORT 8666給整個頁面
> 然後ws的寫法是跟你一致的
> 請問你知道什麼情況下會ERR_CONNECTION_RESE嗎
> 我有查可能是client問slb的時候 回傳sever位置
> Ip有被改變
> 是這樣嗎
> 感謝大大

不好意思 根据你的描述跟提供的信息  我也无法确定是否是你说的那个问题   无法定位到具体问题的所在
