### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by RobKing9** [hezhizheng/go-gin-chat#5]
请问大佬有没有想法添加一些功能 比如说
可以添加好友，个人主页显示好友，私聊好友

**Comment by hezhizheng** [comment]
> 请问大佬有没有想法添加一些功能 比如说 可以添加好友，个人主页显示好友，私聊好友

这个项目原本就是 为熟悉Gin框架跟websocket使用 开发的，一开始也没考虑过实现比较全面的功能，目前私聊是支持在同一聊天室中进行的，后面有时间再考虑加其他功能 @RobKing9
