### ISSUE TITLE
websocket创建连接后无法销毁

### ISSUE THREAD

**Issue by wztzt** [hezhizheng/go-gin-chat#6]
会造成过多驻留协程
![image](https://github.com/hezhizheng/go-gin-chat/assets/127408272/6c725661-1881-4201-b2c5-2a887ce15225)

**Comment by hezhizheng** [comment]
> 会造成过多驻留协程 ![image](https://user-images.githubusercontent.com/127408272/243291716-6c725661-1881-4201-b2c5-2a887ce15225.png)

我排查下，请问你这是用什么方法查看的 @wztzt

**Comment by wztzt** [comment]
> 

websocket主协程没有设置退出条件
